name: Basics
on:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - run: gh issue create --title "Workflow issue" --body "Thank you for creating this issue!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo I am running in parallel job
  third-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - run: echo I am running in sequencial job
    
